// Copyright © 2025 Curt Gilman
// SPDX-License-Identifier: AGPL-3.0-only
// Viae: A geo-centric, journey-focused, federated blog platform

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Viae.Domain.Models;
using Viae.Persistence;

namespace Viae.Services;

/// <summary>
/// Service for managing ActivityPub Ping and Pong activities (Missio/Reflexio).
/// Handles sending pings, receiving pings, and automatically responding with pongs.
/// </summary>
public partial class MissioService(
    IDbContextFactory<ViaeDbContext> dbContextFactory,
    ILogger<MissioService> logger,
    IUriGeneratorService uriGenerator
) : EntityServiceBase(uriGenerator), IMissioService
{
    #region Logging

    [LoggerMessage(
        Level = LogLevel.Information,
        Message = "Creating outbound ping from {Actor} to {To}"
    )]
    private partial void LogCreatingOutboundPing(Uri actor, Uri to);

    [LoggerMessage(
        Level = LogLevel.Information,
        Message = "Created outbound ping with ID {Id} and URI {Uri}"
    )]
    private partial void LogOutboundPingCreated(string id, Uri uri);

    [LoggerMessage(
        Level = LogLevel.Information,
        Message = "Recording inbound ping from {Actor} to {To} with URI {Uri}"
    )]
    private partial void LogRecordingInboundPing(Uri actor, Uri to, Uri uri);

    [LoggerMessage(Level = LogLevel.Information, Message = "Recorded inbound ping with ID {Id}")]
    private partial void LogInboundPingRecorded(string id);

    [LoggerMessage(
        Level = LogLevel.Information,
        Message = "Creating outbound pong from {Actor} to {To} in response to ping {PingUri}"
    )]
    private partial void LogCreatingOutboundPong(Uri actor, Uri to, Uri pingUri);

    [LoggerMessage(
        Level = LogLevel.Information,
        Message = "Created outbound pong with ID {Id} and URI {Uri}"
    )]
    private partial void LogOutboundPongCreated(string id, Uri uri);

    [LoggerMessage(
        Level = LogLevel.Information,
        Message = "Recording inbound pong from {Actor} to {To} for ping {PingUri}"
    )]
    private partial void LogRecordingInboundPong(Uri actor, Uri to, Uri pingUri);

    [LoggerMessage(Level = LogLevel.Information, Message = "Recorded inbound pong with ID {Id}")]
    private partial void LogInboundPongRecorded(string id);

    [LoggerMessage(
        Level = LogLevel.Information,
        Message = "Marking inbound ping {PingId} as ponged"
    )]
    private partial void LogMarkingPingAsPonged(string pingId);

    [LoggerMessage(
        Level = LogLevel.Warning,
        Message = "Inbound ping {PingId} not found when attempting to mark as ponged"
    )]
    private partial void LogPingNotFoundForMarking(string pingId);

    [LoggerMessage(
        Level = LogLevel.Information,
        Message = "Marking outbound ping {PingUri} as pong received"
    )]
    private partial void LogMarkingPingAsPongReceived(Uri pingUri);

    [LoggerMessage(
        Level = LogLevel.Warning,
        Message = "Outbound ping with URI {PingUri} not found when attempting to mark as pong received"
    )]
    private partial void LogOutboundPingNotFound(Uri pingUri);

    #endregion

    /// <inheritdoc />
    public async Task<Admissio> CreateOutboundPingAsync(Uri actor, Uri toUri)
    {
        LogCreatingOutboundPing(actor, toUri);

        using var dbContext = dbContextFactory.CreateDbContext();

        var ping = new Admissio
        {
            Actor = actor,
            To = toUri,
            CreatedAt = DateTime.UtcNow,
        };

        PrepareEntityForInsertion(ping);

        dbContext.Admissiones.Add(ping);
        await dbContext.SaveChangesAsync();

        // ID and URI are auto-generated by PrepareEntityForInsertion
        LogOutboundPingCreated(ping.Id, ping.Uri);

        return ping;
    }

    /// <inheritdoc />
    public async Task<Abmissio> RecordInboundPingAsync(Uri uri, Uri actor, Uri toUri)
    {
        LogRecordingInboundPing(actor, toUri, uri);

        using var dbContext = dbContextFactory.CreateDbContext();

        var ping = new Abmissio
        {
            Uri = uri,
            Actor = actor,
            To = toUri,
            ReceivedAt = DateTime.UtcNow,
        };

        PrepareEntityForInsertion(ping);

        dbContext.Abmissiones.Add(ping);
        await dbContext.SaveChangesAsync();

        LogInboundPingRecorded(ping.Id);

        return ping;
    }

    /// <inheritdoc />
    public async Task<Adreflexio> CreateOutboundPongAsync(Uri actor, Uri toUri, Uri pingUri)
    {
        LogCreatingOutboundPong(actor, toUri, pingUri);

        using var dbContext = dbContextFactory.CreateDbContext();

        var pong = new Adreflexio
        {
            Actor = actor,
            To = toUri,
            PingUri = pingUri,
            CreatedAt = DateTime.UtcNow,
        };

        PrepareEntityForInsertion(pong);

        dbContext.Adreflexiones.Add(pong);
        await dbContext.SaveChangesAsync();

        // ID and URI are auto-generated by PrepareEntityForInsertion
        LogOutboundPongCreated(pong.Id, pong.Uri);

        return pong;
    }

    /// <inheritdoc />
    public async Task<Abreflexio> RecordInboundPongAsync(Uri uri, Uri actor, Uri toUri, Uri pingUri)
    {
        LogRecordingInboundPong(actor, toUri, pingUri);

        using var dbContext = dbContextFactory.CreateDbContext();

        var pong = new Abreflexio
        {
            Uri = uri,
            Actor = actor,
            To = toUri,
            PingUri = pingUri,
            ReceivedAt = DateTime.UtcNow,
        };

        PrepareEntityForInsertion(pong);

        dbContext.Abreflexiones.Add(pong);
        await dbContext.SaveChangesAsync();

        LogInboundPongRecorded(pong.Id);

        return pong;
    }

    /// <inheritdoc />
    public async Task MarkInboundPingAsPongedAsync(string pingId)
    {
        LogMarkingPingAsPonged(pingId);

        using var dbContext = dbContextFactory.CreateDbContext();

        var ping = await dbContext.Abmissiones.FindAsync(pingId);
        if (ping == null)
        {
            LogPingNotFoundForMarking(pingId);
            return;
        }

        ping.PongSent = true;
        ping.PongSentAt = DateTime.UtcNow;
        await dbContext.SaveChangesAsync();
    }

    /// <inheritdoc />
    public async Task MarkOutboundPingAsPongReceivedAsync(Uri pingUri)
    {
        LogMarkingPingAsPongReceived(pingUri);

        using var dbContext = dbContextFactory.CreateDbContext();

        var ping = await dbContext.Admissiones.FirstOrDefaultAsync(p => p.Uri == pingUri);
        if (ping == null)
        {
            LogOutboundPingNotFound(pingUri);
            return;
        }

        ping.PongReceived = true;
        ping.PongReceivedAt = DateTime.UtcNow;
        await dbContext.SaveChangesAsync();
    }

    /// <inheritdoc />
    public async Task<Admissio?> GetOutboundPingAsync(string id)
    {
        using var dbContext = dbContextFactory.CreateDbContext();
        return await dbContext.Admissiones.FindAsync(id);
    }

    /// <inheritdoc />
    public async Task<Abmissio?> GetInboundPingAsync(string id)
    {
        using var dbContext = dbContextFactory.CreateDbContext();
        return await dbContext.Abmissiones.FindAsync(id);
    }

    /// <inheritdoc />
    public async Task<List<Admissio>> GetOutboundPingsAsync(int limit = 100)
    {
        using var dbContext = dbContextFactory.CreateDbContext();
        return await dbContext
            .Admissiones.OrderByDescending(p => p.CreatedAt)
            .Take(limit)
            .ToListAsync();
    }

    /// <inheritdoc />
    public async Task<List<Abmissio>> GetInboundPingsAsync(int limit = 100)
    {
        using var dbContext = dbContextFactory.CreateDbContext();
        return await dbContext
            .Abmissiones.OrderByDescending(p => p.ReceivedAt)
            .Take(limit)
            .ToListAsync();
    }
}
