// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Viae.Domain.Models;
using Viae.Persistence;

#nullable disable

namespace Viae.Persistence.Migrations
{
    [DbContext(typeof(ViaeDbContext))]
    partial class ViaeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:und_nodiac", "und-u-ks-level1,und-u-ks-level1,icu,False")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "origo", new[] { "domesticus", "externus" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoliumLocus", b =>
                {
                    b.Property<string>("FoliosId")
                        .HasColumnType("char(11)");

                    b.Property<string>("LocaId")
                        .HasColumnType("char(11)");

                    b.HasKey("FoliosId", "LocaId");

                    b.HasIndex("LocaId");

                    b.ToTable("FoliumLocus");
                });

            modelBuilder.Entity("FoliumThema", b =>
                {
                    b.Property<string>("FoliosId")
                        .HasColumnType("char(11)");

                    b.Property<string>("ThemataId")
                        .HasColumnType("char(11)");

                    b.HasKey("FoliosId", "ThemataId");

                    b.HasIndex("ThemataId");

                    b.ToTable("FoliumThema");
                });

            modelBuilder.Entity("LocusThema", b =>
                {
                    b.Property<string>("LocaId")
                        .HasColumnType("char(11)");

                    b.Property<string>("ThemataId")
                        .HasColumnType("char(11)");

                    b.HasKey("LocaId", "ThemataId");

                    b.HasIndex("ThemataId");

                    b.ToTable("LocusThema");
                });

            modelBuilder.Entity("Viae.Domain.Models.Abmissio", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(11)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PongSent")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PongSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Abmissiones");
                });

            modelBuilder.Entity("Viae.Domain.Models.Abreflexio", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(11)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PingUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Abreflexiones");
                });

            modelBuilder.Entity("Viae.Domain.Models.Admissio", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(11)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PongReceived")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PongReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Admissiones");
                });

            modelBuilder.Entity("Viae.Domain.Models.Adreflexio", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(11)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PingUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Adreflexiones");
                });

            modelBuilder.Entity("Viae.Domain.Models.Folium", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(11)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean");

                    b.Property<Origo>("Origo")
                        .HasColumnType("origo");

                    b.Property<string>("PersonaId")
                        .IsRequired()
                        .HasColumnType("char(11)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Uri")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsDraft");

                    b.HasIndex("PersonaId");

                    b.HasIndex("PublishedAt");

                    b.ToTable("Folios");
                });

            modelBuilder.Entity("Viae.Domain.Models.Locus", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(11)");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<Point>("Coordinates")
                        .IsRequired()
                        .HasColumnType("geography(Point, 4326)");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("und_nodiac");

                    b.Property<string>("OsmId")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Coordinates");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Coordinates"), "gist");

                    b.HasIndex("Name");

                    b.ToTable("Loca");
                });

            modelBuilder.Entity("Viae.Domain.Models.Persona", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(11)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<Guid?>("CognitoUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<Origo>("Origo")
                        .HasColumnType("origo");

                    b.Property<string>("PrivateKey")
                        .HasColumnType("text");

                    b.Property<string>("PublicKey")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Uri")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CognitoUserId")
                        .IsUnique();

                    b.HasIndex("Email");

                    b.HasIndex("Uri")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Personae");
                });

            modelBuilder.Entity("Viae.Domain.Models.Thema", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(11)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Themata");
                });

            modelBuilder.Entity("Viae.Domain.Models.Vestigium", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(11)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HappenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocusId")
                        .IsRequired()
                        .HasColumnType("char(11)");

                    b.Property<Origo>("Origo")
                        .HasColumnType("origo");

                    b.Property<string>("PersonaId")
                        .IsRequired()
                        .HasColumnType("char(11)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TombstonedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocusId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Vestigia");
                });

            modelBuilder.Entity("FoliumLocus", b =>
                {
                    b.HasOne("Viae.Domain.Models.Folium", null)
                        .WithMany()
                        .HasForeignKey("FoliosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viae.Domain.Models.Locus", null)
                        .WithMany()
                        .HasForeignKey("LocaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoliumThema", b =>
                {
                    b.HasOne("Viae.Domain.Models.Folium", null)
                        .WithMany()
                        .HasForeignKey("FoliosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viae.Domain.Models.Thema", null)
                        .WithMany()
                        .HasForeignKey("ThemataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LocusThema", b =>
                {
                    b.HasOne("Viae.Domain.Models.Locus", null)
                        .WithMany()
                        .HasForeignKey("LocaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viae.Domain.Models.Thema", null)
                        .WithMany()
                        .HasForeignKey("ThemataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Viae.Domain.Models.Folium", b =>
                {
                    b.HasOne("Viae.Domain.Models.Persona", "Persona")
                        .WithMany("Folios")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Viae.Domain.Models.Vestigium", b =>
                {
                    b.HasOne("Viae.Domain.Models.Locus", "Locus")
                        .WithMany()
                        .HasForeignKey("LocusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viae.Domain.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locus");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Viae.Domain.Models.Persona", b =>
                {
                    b.Navigation("Folios");
                });
#pragma warning restore 612, 618
        }
    }
}
